# @name get-prompts
GET http://localhost:3333/prompts

###

# @name Upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="example1.mp3"
Content-Type: audio/mpeg

< ./example1.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transition
POST http://localhost:3333/videos/cedc357f-4c8a-4145-8df8-6a7cfa181a18/transcription
Content-Type: application/json

{
    "prompt": "cangaço"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

# Para longos blocos de texto, basta colocar sua variável entre 3 carateres de cada lado (abaixo eu usei 3 acentos de cada lado)
# Exemplo: bla bla bla: '''{variavel_aqui}'''
{
    "videoId": "cedc357f-4c8a-4145-8df8-6a7cfa181a18",
    "temperature": 0.2,
    "prompt": "gere um resumo dessa transcrição de video informada a seguir: '''{transcription}'''"
}